services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
    - '8080:80'
    volumes:
    - ./website:/usr/local/apache2/htdocs
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: baseDB
  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:5000